package csharp

import (
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
)

// codebaseIndex stores discovered type definitions and their locations for
// the entire C# source tree. It enables wrapper resolution and entity lookup.
type codebaseIndex struct {
	mu sync.RWMutex

	// definedTypes maps unqualified type name -> file path
	definedTypes map[string]string

	// typeNamespaces maps unqualified type name -> namespace
	typeNamespaces map[string]string

	// qualifiedTypes maps "Namespace.TypeName" -> file path
	qualifiedTypes map[string]string

	// typeKinds maps "Namespace.TypeName" -> kind (class, interface, etc.)
	typeKinds map[string]string

	// refCounts maps entity name -> number of references
	refCounts map[string]int

	// partialTypes tracks partial class declarations for merging
	// maps "Namespace.TypeName" -> list of file paths
	partialTypes map[string][]string

	// fileAnalyses caches parsed file analysis
	fileAnalyses map[string]*fileAnalysis
}

// emptyIndex returns a new, fully-initialised (but empty) codebaseIndex.
func emptyIndex() *codebaseIndex {
	return &codebaseIndex{
		definedTypes:   make(map[string]string),
		typeNamespaces: make(map[string]string),
		qualifiedTypes: make(map[string]string),
		typeKinds:      make(map[string]string),
		refCounts:      make(map[string]int),
		partialTypes:   make(map[string][]string),
		fileAnalyses:   make(map[string]*fileAnalysis),
	}
}

// FileForType returns the file path for a type by its unqualified name.
func (idx *codebaseIndex) FileForType(name string) (string, bool) {
	idx.mu.RLock()
	defer idx.mu.RUnlock()
	v, ok := idx.definedTypes[name]
	return v, ok
}

// NamespaceForType returns the namespace for a type by its unqualified name.
func (idx *codebaseIndex) NamespaceForType(name string) string {
	idx.mu.RLock()
	defer idx.mu.RUnlock()
	return idx.typeNamespaces[name]
}

// HasType reports whether the index contains a type with the given qualified name.
func (idx *codebaseIndex) HasType(qualifiedName string) bool {
	idx.mu.RLock()
	defer idx.mu.RUnlock()
	_, ok := idx.qualifiedTypes[qualifiedName]
	return ok
}

// skipDirs contains directory names that should be excluded from scanning.
var skipDirs = map[string]bool{
	".git":         true,
	"vendor":       true,
	"node_modules": true,
	"obj":          true,
	"bin":          true,
	"packages":     true,
	".vs":          true,
	"TestResults":  true,
	"artifacts":    true,
}

// isTestPath returns true if the path appears to be a test project/file.
func isTestPath(path string) bool {
	lower := strings.ToLower(path)
	parts := strings.Split(strings.ReplaceAll(lower, "\\", "/"), "/")
	for _, part := range parts {
		if strings.HasSuffix(part, "tests") ||
			strings.HasSuffix(part, "test") ||
			strings.HasSuffix(part, ".tests") ||
			strings.HasSuffix(part, ".test") ||
			part == "testassets" ||
			part == "testdata" ||
			part == "benchmarks" ||
			part == "perf" ||
			part == "samples" {
			return true
		}
	}
	return false
}

// isGeneratedFile returns true if the file appears to be auto-generated.
func isGeneratedFile(content []byte) bool {
	// Check first 1KB for auto-generated markers
	check := content
	if len(check) > 1024 {
		check = check[:1024]
	}
	s := string(check)
	return strings.Contains(s, "<auto-generated") ||
		strings.Contains(s, "// <auto-generated>") ||
		strings.Contains(s, "//----------------------") && strings.Contains(s, "auto-generated")
}

// buildCodebaseIndex walks the source tree and builds the type index.
func buildCodebaseIndex(repoPath string, sourceDirs []string) (*codebaseIndex, error) {
	idx := emptyIndex()

	var roots []string
	if len(sourceDirs) > 0 {
		for _, dir := range sourceDirs {
			roots = append(roots, filepath.Join(repoPath, dir))
		}
	} else {
		roots = []string{repoPath}
	}

	for _, root := range roots {
		info, err := os.Stat(root)
		if err != nil {
			if os.IsNotExist(err) {
				log.Printf("WARNING: discovery root %q does not exist, skipping", root)
				continue
			}
			return nil, err
		}
		if !info.IsDir() {
			log.Printf("WARNING: discovery root %q is not a directory, skipping", root)
			continue
		}

		walkErr := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				log.Printf("WARNING: walking %s: %v", path, err)
				return nil
			}

			if d.IsDir() {
				name := d.Name()
				if skipDirs[name] {
					return filepath.SkipDir
				}
				// Skip test directories
				if isTestPath(path) {
					return filepath.SkipDir
				}
				return nil
			}

			if !strings.HasSuffix(strings.ToLower(d.Name()), ".cs") {
				return nil
			}

			// Skip designer files and other generated patterns
			lower := strings.ToLower(d.Name())
			if strings.HasSuffix(lower, ".designer.cs") ||
				strings.HasSuffix(lower, ".generated.cs") ||
				strings.HasSuffix(lower, ".g.cs") ||
				strings.HasSuffix(lower, ".g.i.cs") {
				return nil
			}

			// Skip test files by name pattern
			if strings.HasSuffix(lower, "_test.cs") ||
				strings.HasSuffix(lower, "tests.cs") ||
				strings.HasSuffix(lower, "test.cs") {
				return nil
			}

			content, err := os.ReadFile(path)
			if err != nil {
				log.Printf("WARNING: read %s: %v", path, err)
				return nil
			}

			// Skip generated files
			if isGeneratedFile(content) {
				return nil
			}

			analysis := parseFile(content)
			if analysis == nil {
				return nil
			}

			idx.mu.Lock()
			idx.fileAnalyses[path] = analysis

			for _, td := range analysis.Types {
				if td.Visibility != "public" && td.Visibility != "protected" {
					continue
				}
				qualifiedName := td.qualifiedName()
				idx.qualifiedTypes[qualifiedName] = path
				idx.typeKinds[qualifiedName] = td.Kind
				idx.definedTypes[td.Name] = path
				idx.typeNamespaces[td.Name] = td.Namespace

				if td.IsPartial {
					idx.partialTypes[qualifiedName] = append(idx.partialTypes[qualifiedName], path)
				}
			}
			idx.mu.Unlock()

			return nil
		})
		if walkErr != nil {
			return nil, walkErr
		}
	}

	// Count references
	idx.mu.Lock()
	for _, analysis := range idx.fileAnalyses {
		seen := make(map[string]bool)
		for _, ref := range analysis.References {
			if !seen[ref] {
				idx.refCounts[ref]++
				seen[ref] = true
			}
		}
	}
	idx.mu.Unlock()

	log.Printf("Indexed %d C# types from %s", len(idx.qualifiedTypes), repoPath)
	return idx, nil
}

// priority returns the crawl priority for a type based on reference count.
func (idx *codebaseIndex) priority(name string) int {
	idx.mu.RLock()
	refs := idx.refCounts[name]
	idx.mu.RUnlock()

	if refs >= 50 {
		return 0
	}
	if refs >= 10 {
		return 1
	}
	return 2
}

// buildEntityList returns sorted entity identifiers for all discovered types.
func (idx *codebaseIndex) buildEntityList() []string {
	type item struct {
		id       string
		priority int
		sortKey  string
	}

	idx.mu.RLock()
	defer idx.mu.RUnlock()

	// For partial types, only emit one entityID (using first file found)
	emittedPartials := make(map[string]bool)

	var items []item
	for qualifiedName, path := range idx.qualifiedTypes {
		// Skip duplicate partial type entries
		if paths, isPartial := idx.partialTypes[qualifiedName]; isPartial {
			if emittedPartials[qualifiedName] {
				continue
			}
			emittedPartials[qualifiedName] = true
			// Use the first file for the entity ID
			path = paths[0]
		}

		id := path + "#" + qualifiedName
		items = append(items, item{
			id:       id,
			priority: idx.refCounts[qualifiedName],
			sortKey:  strings.ToLower(qualifiedName),
		})
	}

	sort.SliceStable(items, func(i, j int) bool {
		pi := priorityBucket(items[i].priority)
		pj := priorityBucket(items[j].priority)
		if pi != pj {
			return pi < pj
		}
		return items[i].sortKey < items[j].sortKey
	})

	out := make([]string, 0, len(items))
	seen := make(map[string]bool)
	for _, it := range items {
		if seen[it.id] {
			continue
		}
		seen[it.id] = true
		out = append(out, it.id)
	}
	return out
}

func priorityBucket(refs int) int {
	if refs >= 50 {
		return 0
	}
	if refs >= 10 {
		return 1
	}
	return 2
}
